CREATE TABLE users (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    userId VARCHAR(36) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    FOREIGN KEY (userId) REFERENCES users(id)
);

CREATE TABLE comments (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    postId VARCHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    FOREIGN KEY (postId) REFERENCES posts(id)
);

-- @block
-- DELETE FROM users;
-- DELETE FROM posts;
-- DELETE FROM comments;